config/routes.rb
Taba::Application.routes.draw do

  namespace "admin" do
    root :to => "home#index"
    resources :projects
    resources :clients
    resources :tasks
  end
  get "projects/index"
  get "projects/show"
  get "clients/index"

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  validates_presence_of :name, :email, :contact
  validates_uniqueness_of :email

  def self.tasks
    Rails.cache.fetch "client_task_listZ" do
      self.find(:all, :limit => 10)
    end
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  validates_numericality_of :amount
  validates_presence_of :client_id, :invoice_number, :due_at, :sent_at, :subject, :remit_to


end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :project
  has_one :task
  validates_numericality_of :hours
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  respond_to :html
  before_filter :get_client, :except => [:index, :create]

  def index
    @clients = Client.all
  end

  def show
    @client
  end

  def new
  end

  def edit
  end

  def create
    @client = Client.new(@clientParams)
    if @client.save
      redirect_to admin_clients_path, :notice => "Created..."
    else
      flash[:alert] = "Error"
      render :action => "new"
    end
  end

  def update
    if @client.update_attributes(@clientParams)
      redirect_to admin_clients_path, :notice => "Updated ..." 
    else
      flash[:alert] = "Error"
      render :action => "edit"
    end
  end

  def destroy
    if @client.destroy
      redirect_to admin_clients_path, :notice => "Destroyed ..."
    else
      flash[:alert] = "Error"
      render :action => "edit"
    end
  end

  private
    def get_client
      @client = params[:id].present? ? Client.find(params[:id]) : Client.new
      @clientParams = params[:client].present? ? params[:client].permit(:name, :email, :contact) : []
    end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  respond_to :html
  before_filter :get_project, :except => [:index,:create]

  def index
      @projects = Project.all
      
  end

  def show
    @project
  end

  def new

  end

  def edit

  end

  def create
      @project = Project.new(@projectParams)
      if @project.save
        redirect_to admin_projects_path, :notice => "Created ..."
      else
        flash[:alert] = "Error"
        render :action => 'new'
      end
  end

  def update
      if @project.update_attributes(@projectParams)
        redirect_to admin_projects_path, :notice => "Updated ..."
      else
        flash[:alert] = "Error"
        render :action => 'edit'
      end
  end

  def destroy
      
      if @project.destroy
        redirect_to admin_projects_path, :notice => "Destroyed ..."
      else
        flash[:alert] = "Error"
        render :action => 'edit'
      end
  end

  private
    def get_project
      @project = params[:id].present? ? Project.find(params[:id]) : Project.new
      @projectParams = params[:project].present? ? params[:project].permit(:client_id, :name, :description, :budget) : []
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/clients/edit.html.haml
%h1 Edit Client
%p
  = semantic_form_for [:admin,@client] do |f|
    =f.inputs
    =f.actions
    
  

app/views/admin/clients/index.html.haml
%h1 Clients

%ul
  -@clients.each do |c|
    %li=link_to(c.name, edit_admin_client_path(c))
%hr
=link_to("new", new_admin_client_path)

app/views/admin/clients/new.html.haml
%h1 New Client
%p
  =semantic_form_for [:admin, @client] do |f|
    =f.inputs
    =f.actions

app/views/admin/projects/edit.html.haml
%h1
  = link_to('Projects', admin_projects_path)
  >> #{@project.name}
  %p
    =semantic_form_for [:admin,@project] do |f|
      =f.inputs
      =f.actions
%hr
= link_to("New", new_admin_project_path)
%br
= link_to 'Destroy', [:admin,@project], :confirm => 'Are you sure?', :method => :delete

app/views/admin/projects/index.html.haml
%h1 Projects
%ul
  -@projects.each do |c|
    %li=link_to(c.name, edit_admin_project_path(c))
%hr
=link_to("new",new_admin_project_path)

app/views/admin/projects/new.html.haml
%h1
  = link_to('Projects', admin_projects_path)
  >> New
  %p
    =semantic_form_for [:admin,@project] do |f|
      =f.inputs
      =f.actions

app/views/clients/index.html.haml
%h1 Clients#index
%p Find me in app/views/clients/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Taba
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #flash
    - unless notice.blank?
      .success
        = notice
    - unless alert.blank?
      .alert
        = alert
    #menu
      %ul
        %li=link_to "Clients", admin_clients_path
        %li=link_to "Projects", admin_projects_path
        %li=link_to "Tasks", admin_tasks_path
        -# %li=link_to "Invoices", admin_invoices_path
    #content
      .container
        = yield

app/views/projects/index.html.haml
%h1 Projects#index
%p Find me in app/views/projects/index.html.haml

app/views/projects/show.html.haml
%h1 Projects#show
%p Find me in app/views/projects/show.html.haml